### ISSUE TITLE
Opening existing .uml files does not work

### ISSUE THREAD

**Issue by ltzur** [claeis/umleditor#43]
Mit dem neusten umleditor (3.7.4. vom 29.09.2020) lassen sich bestehende .uml-Dateien nicht mehr öffnen. Im log-Bereich wird die Fehlermeldung "[Laufzeit-Fehler] fileopen->wrong number of arguments[java.io.IOException: wrong number of arguments]" ausgegeben.

**Comment by Pierre-de-la-Verre** [comment]
Bestätigt. Vor 30min erstellt, geändert, gespeichert - jetzt dieses Problem.
Eine Stunde vorher ging es noch - gleicher PC, gleiche Daten.
Herumgespielt habe ich allerdings mit den Spracheinstellungen - vielleicht hier ein Problem?

Hier die erweiterte Fehlermeldung:
`java.io.IOException: wrong number of arguments
	at ch.ehi.umleditor.xmiuml.ehi.XMLInterlisDecoder.parse(XMLInterlisDecoder.java:137)
	at ch.ehi.umleditor.xmiuml.ehi.XMLInterlisDecoder.decode(XMLInterlisDecoder.java:49)
	at ch.ehi.umleditor.xmiuml.PersistenceService.readFile(PersistenceService.java:45)
	at ch.ehi.umleditor.application.LauncherView.openFile(LauncherView.java:4275)
	at ch.ehi.umleditor.application.LauncherView.mniOpenFile(LauncherView.java:3542)
	at ch.ehi.umleditor.application.LauncherView.connEtoC27(LauncherView.java:813)
	at ch.ehi.umleditor.application.LauncherView.access$6600(LauncherView.java:56)
	at ch.ehi.umleditor.application.LauncherView$IvjEventHandler.tbbOpenAction_actionPerformed(LauncherView.java:252)
	at ch.softenvironment.view.ToolBar.fireTbbOpenAction_actionPerformed(ToolBar.java:443)
	at ch.softenvironment.view.ToolBar.connEtoC1(ToolBar.java:113)
	at ch.softenvironment.view.ToolBar.access$100(ToolBar.java:32)
	at ch.softenvironment.view.ToolBar$IvjEventHandler.actionPerformed(ToolBar.java:58)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by Pierre-de-la-Verre** [comment]
@ltzur 
versuche, die Sprache des Programm zu ändern. Scheint eine Spur zu sein ..

**Comment by claeis** [comment]
Welche Spracheinstellung?
  a) Extras/Sprache der Modelldarstellung...
  b) Hilfe/Sprache...

**Comment by Pierre-de-la-Verre** [comment]
b) Hilfe/Sprache...

Ablauf:
- Programm (auf Deutsch) starten, bestehende UML öffnen
- Hilfe - "Language" (nicht Sprache): Die Liste steht auf "en_US", obwohl deutsch aktiv ist
- OK klicken
- Programm schliessen, nicht speichern
- Programm starten (auf English), bestehende UML öffnen -> Error

- Help- "Language" : de wählen
- Neustart - alles OK

**Comment by claeis** [comment]
Merci, habs gefunden, Problem hat nichts mit der Sprache zu tun.

**Comment by claeis** [comment]
Bitte mit neuem [SNAPSHOT](https://jars.interlis.ch/ch/interlis/umleditor/3.7.5-SNAPSHOT/umleditor-3.7.5-20201027.091216-2-bindist.zip)  testen

**Comment by Pierre-de-la-Verre** [comment]
@ltzur 
verfolgst du das Thema noch? Wirst du das auch testen?

**Comment by ltzur** [comment]
Ich habe das soeben mit verschiedenen älteren .uml-Datei getestet und keine Probleme mehr festgestellt. Danke für die Korrektur!

**Comment by Pierre-de-la-Verre** [comment]
> 
> 
> Bitte mit neuem [SNAPSHOT](https://jars.interlis.ch/ch/interlis/umleditor/3.7.5-SNAPSHOT/umleditor-3.7.5-20201027.091216-2-bindist.zip) testen
Der von mir oben beschriebene Ablauf funktioniert auch bei mir fehlerfrei. Danke
