### ISSUE TITLE
ili24: INTERLIS Import schlägt fehl bei Modell CHBase GEOMETRY

### ISSUE THREAD

**Issue by beistehen** [claeis/umleditor#57]
Der Import des Modells [CHBase_Part1_GEOMETRY_V2.ili](https://models.geo.admin.ch/CH/CHBase_Part1_GEOMETRY_V2.ili) (INTERLIS 2.4) schlägt fehl mit einer NPE (umleditor v3.8.1):

```
java.lang.NullPointerException
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitType(TransferFromIli2cMetamodel.java:1481)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitDomainDef(TransferFromIli2cMetamodel.java:1372)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitElements(TransferFromIli2cMetamodel.java:1785)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitModel(TransferFromIli2cMetamodel.java:1258)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitElements(TransferFromIli2cMetamodel.java:1764)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitTransferDescription(TransferFromIli2cMetamodel.java:1891)
	at ch.ehi.umleditor.interlis.iliimport.ImportInterlis.readIliFile(ImportInterlis.java:80)
	at ch.ehi.umleditor.interlis.iliimport.ImportInterlis.doImport(ImportInterlis.java:168)
	at ch.ehi.umleditor.application.LauncherView.mniInterlisImport(LauncherView.java:3434)
	at ch.ehi.umleditor.application.LauncherView.connEtoC14(LauncherView.java:576)
	at ch.ehi.umleditor.application.LauncherView.access$2100(LauncherView.java:56)
<...snip ...>
```

**Comment by claeis** [comment]
Als Workaround folgende Datei verwenden:
[CHBase_Part1_GEOMETRY_V2.zip](https://github.com/claeis/umleditor/files/8096248/CHBase_Part1_GEOMETRY_V2.zip)

**Comment by claeis** [comment]
[DM_Flex-uml.zip](https://github.com/claeis/umleditor/files/8096252/DM_Flex-uml.zip)

**Comment by claeis** [comment]
MULTIPOLYLINE, MULTISURFACE fails. To fix: extend uml-metamodel, ili-import, ili-export, GUI

**Comment by claeis** [comment]
MULTCOORD auch ergänzen.
